name: Python Linter

on:
  push:
    paths:
      - ".github/workflows/linter.yml"
      - "python/**"
  workflow_dispatch:

jobs:
  lint-python:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter (Python only)
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKSPACE: ./python
          # Only enable Python validation
          VALIDATE_PYTHON: true
          
          # Choose ONE main Python linter (or enable multiple carefully)
          VALIDATE_PYTHON_PYLINT: true
          # VALIDATE_PYTHON_FLAKE8: false
          # VALIDATE_PYTHON_BLACK: false
          # VALIDATE_PYTHON_ISORT: false
          # VALIDATE_PYTHON_MYPY: false
          
          # Disable ALL other languages
          VALIDATE_CSS: false
          VALIDATE_ENV: false
          VALIDATE_GO: false
          VALIDATE_JSON: false
          VALIDATE_JS: false
          VALIDATE_TS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: false
          VALIDATE_DOCKER: false
          VALIDATE_BASH: false
          VALIDATE_TERRAFORM: false
          VALIDATE_POWERSHELL: false
          VALIDATE_RUBY: false
          VALIDATE_COFFEE: false
          VALIDATE_KOTLIN: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_CLOJURE: false
          VALIDATE_PROTOBUF: false
          VALIDATE_HTML: false

      - name: Print the contents
        if: always() 
        run: ls -lrt

      - name: Upload Linter Reports
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: super-linter-results
          path: |
            super-linter.log
            github/logs/super-linter.log
            super-linter-output/*
