name: Linter

on:
  push:
    paths:
      - ".github/workflows/linter.yml"
      - "python/**"
  workflow_dispatch:


jobs:
  lintint-job:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKSPACE: ./python

      - name: print the contents
        if: always() 
        run: ls -lrt

      - name: Upload Linter Reports
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: super-linter-results
          path: super-linter-output/*
