name: Playground

on: 
    workflow_dispatch: 
    
jobs:
    inspect-java:
        runs-on: ubuntu-latest
        steps:
            - name: Run a multi-line script
              run: |
                echo "=== Java Version ==="
                java -version
                echo "\n=== Java Location ==="
                which java
                echo "\n=== Java Home ==="
                echo $JAVA_HOME





            
                
